language: python
python: 3.6

branches:
  only:
  - master

install:
  - wget https://github.com/spf13/hugo/releases/download/v0.22/hugo_0.22_Linux-64bit.tar.gz
  - tar -xvf hugo_0.22_Linux-64bit.tar.gz hugo
  - pip install pygments

script:
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
