baseURL = "http://wiki.seisman.info/"
languageCode = "zh-cmn-Hans"
title = "SeisMan's Wiki"

theme = "hugo-theme-wiki"
hasCJKLanguage = true
pygmentsCodeFences = true
pygmentsStyle = 'tango'

disableRSS = true
disableSitemap = true
enableGitInfo = true
pluralizeListTitles = false

[author]
    name = "seisman"

[params]
    since = 2017

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/seisman/wiki"
    weight = 2

[[menu.main]]
    name = "Edit on GitHub"
    identifier = 'edit_on_github'
    url = "https://github.com/seisman/wiki/blob/master/content"
    weight = 3
