baseURL = "http://wiki.seisman.info/"
languageCode = "zh-cn"
title = "SeisMan's Wiki"

theme = "hugo-theme-wiki"
hasCJKLanguage = true
pygmentsCodeFences = true
pygmentsStyle = 'tango'

[author]
    name = "seisman"

[params]
    since = 2017
    copyright = "Powered by [Hugo](https://gohugo.io)."

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/seisman/wiki"
    weight = 2

[[menu.main]]
    name = "Edit on GitHub"
    identifier = 'edit_on_github'
    url = "https://github.com/seisman/wiki/blob/master/content"
    weight = 3
